/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict visual attention for one PNG/JPEG image */
        post: operations["create_analysis_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Analysis Id */
            analysis_id: string;
            /**
             * Created At
             * @description UTC ISO 8601 timestamp.
             */
            created_at: string;
            density: components["schemas"]["DensityGrid"];
            heatmap: components["schemas"]["Heatmap"];
            image: components["schemas"]["ImageInfo"];
            model: components["schemas"]["ModelInfo"];
            processing: components["schemas"]["Processing"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1";
        };
        /** Body_create_analysis_v1_analyses_post */
        Body_create_analysis_v1_analyses_post: {
            /** Image */
            image: string;
        };
        /** DensityGrid */
        DensityGrid: {
            /**
             * Data
             * @description Base64 of width*height little-endian float32 probabilities.
             */
            data: string;
            /**
             * Encoding
             * @constant
             */
            encoding: "base64-float32-le";
            /**
             * Height
             * @description Grid rows. Row r covers y in [r/height, (r+1)/height).
             */
            height: number;
            /**
             * Layout
             * @constant
             */
            layout: "row-major-top-left";
            /**
             * Sum
             * @description Sum of the decoded float32 values (1 up to float32 rounding).
             */
            sum: number;
            /**
             * Width
             * @description Grid columns. Column c covers x in [c/width, (c+1)/width).
             */
            width: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Code
             * @enum {string}
             */
            code: "invalid_request" | "invalid_image" | "payload_too_large" | "unsupported_media_type" | "invalid_dimensions" | "model_unavailable" | "inference_failed" | "internal_error" | "not_found";
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Model Ready */
            model_ready: boolean;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Heatmap */
        Heatmap: {
            /**
             * Color Scale
             * @constant
             */
            color_scale: "relative-to-image-max";
            /** Colormap */
            colormap: string;
            /** Data Url */
            data_url: string;
            /** Height */
            height: number;
            /**
             * Mime Type
             * @constant
             */
            mime_type: "image/png";
            /** Width */
            width: number;
        };
        /** ImageInfo */
        ImageInfo: {
            /**
             * Height
             * @description Height in pixels after EXIF orientation was applied.
             */
            height: number;
            /**
             * Width
             * @description Width in pixels after EXIF orientation was applied.
             */
            width: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Citation */
            citation: string;
            /** License Note */
            license_note: string;
            /**
             * Name
             * @description Model family, e.g. 'DeepGaze IIE'.
             */
            name: string;
            /** Source Url */
            source_url: string;
            /**
             * Version
             * @description Pinned code commit and weights hash identifier.
             */
            version: string;
            /** Weights Sha256 */
            weights_sha256: string;
        };
        /** Processing */
        Processing: {
            /** Alpha Composited On White */
            alpha_composited_on_white: boolean;
            /** Centerbias */
            centerbias: string;
            /** Device */
            device: string;
            /** Exif Orientation */
            exif_orientation: number | null;
            /** Inference Ms */
            inference_ms: number;
            /** Model Input Height */
            model_input_height: number;
            /** Model Input Width */
            model_input_width: number;
            /** Orientation Applied */
            orientation_applied: boolean;
            /** Resampling */
            resampling: string;
            /**
             * Source Format
             * @enum {string}
             */
            source_format: "PNG" | "JPEG";
            /** Source Mode */
            source_mode: string;
            /** Total Ms */
            total_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_analysis_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_analysis_v1_analyses_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
